openapi: "3.0.3"

info:
  title: "Shop Review API"
  version: "1.0.0"

paths: {}

components:
  schemas:
    SampleInt:
      type: integer
      minimum: 0
      # 最小値を含むので、false
      exclusiveMinimum: false
      maximum: 100
      # 100未満
      exclusiveMaximum: true
    SampleString:
      type: string
      nullable: true
      minLength: 10
      maxLength: 20
    SampleBoolean:
      type: boolean
